
---
- name: create user by using the variable
  hosts: production
  vars:
    name: mohamed
    user_pass: "12345"
  tasks:
    - name: create a user called {{ user_name }}
      user:
        name: "{{ user_name }}"
        password: "{{ user_pass | password_hash('sha512')}}"
        state: present
      register: user_info

    - name: show the register file value
      debug:
       var: user_info
